version: '3'
services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
  gem:
    build: .
    volumes:
      - .:/app
    depends_on:
      - azurite
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=azurite:10000/devstoreaccount1;QueueEndpoint=azurite:10001/devstoreaccount1;
